{"name": "test_s3_file_present", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'terraform_outputs.json'", "trace": "s3_client = <botocore.client.S3 object at 0x000001A1845807C0>\n\n    @allure.feature(\"S3 Tests\")\n    @allure.story(\"Check File Presence\")\n    def test_s3_file_present(s3_client):\n    \n>       outputs_tf = get_terraform_outputs()\n\nallure_pytest_test.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_terraform_outputs():\n>       with open('terraform_outputs.json') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'terraform_outputs.json'\n\nallure_pytest_test.py:8: FileNotFoundError"}, "start": 1697550445844, "stop": 1697550445844, "uuid": "475face9-f256-47ed-8c11-46d6ed84b9dd", "historyId": "73490472b191f2c9b472859154f6921b", "testCaseId": "73490472b191f2c9b472859154f6921b", "fullName": "allure_pytest_test#test_s3_file_present", "labels": [{"name": "feature", "value": "S3 Tests"}, {"name": "story", "value": "Check File Presence"}, {"name": "suite", "value": "allure_pytest_test"}, {"name": "host", "value": "WKS0002834571"}, {"name": "thread", "value": "28372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_pytest_test"}]}